### ISSUE TITLE
The type 'Expression<>' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by OscarKoo** [ionutneagos/efcore-automaticmigrations#1]
MigrateToLatestVersion (v7.0.4) threw the exception if the Index has been used in Fluent API (IEntityTypeConfiguration) with .net 7.0.

please check, thanks!

EFCore.AutomaticMigrations.MigrateDatabaseException
  HResult=0x80131500
  Message=Compilation failed. Error: The type 'Expression<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=EFCore.AutomaticMigrations
  StackTrace:
   at EFCore.AutomaticMigrations.Migrate`2.Compile[T](String source, IEnumerable`1 references)
   at EFCore.AutomaticMigrations.Migrate`2.CompileSnapshot(Assembly migrationAssembly, String source)
   at EFCore.AutomaticMigrations.Migrate`2.RunMigrations()
   at EFCore.AutomaticMigrations.MigrateDatabaseToLatestVersionExtensions.MigrateToLatestVersion[TContext,TMigrationsOptions](TContext context, TMigrationsOptions options)

**Comment by OscarKoo** [comment]
@ionutneagos Thank you for your response.

Here is the code:
`builder.HasIndex(e => new { e.AreaId, e.Site }).IncludeProperties(e => e.UserId).HasDatabaseName("IX_tRequest_AreaId")
`

btw. The first time it worked, but the next time it failed. it seems something wrong with the "Snapshot" part. 

![image](https://user-images.githubusercontent.com/14313034/229672353-673980d2-bf8c-4d4f-bccf-c2ecfd6c6c17.png)

**Comment by ionutneagos** [comment]
@OscarKoo - Unfortunately I'm not able to reproduce. I used bellow configurations:

> # Entity

```
public class Sample
 {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        public string UserId { get; set; }
        [Required]
        public int AreaId { get; set; }

        public User User { get; set; }
        public Area Area { get; set; }
 }
```
> # SampleConfiguration

```
public void Configure(EntityTypeBuilder<Sample> builder)
{
            builder.ToTable(nameof(Sample));

            builder.HasKey(sample => sample.Id);
            builder.Property(sample => sample.Id).ValueGeneratedOnAdd();

            builder.HasOne(t => t.User)
                .WithMany(t => t.Samples)
                .HasForeignKey(t => t.UserId);

            builder.HasIndex(e => new { e.AreaId, e.Name })
                   .IncludeProperties(e => e.UserId)
                   .HasDatabaseName("IX_tRequest_AreaId");
}
```

Can you please confirm if you are targeting correctly the .net version?  System.Linq.Expressions, Version=6.0.0.0 is used by .net 6 not .7? 
A possible option could be a reference from another package which is targeting .net 6.

**Comment by OscarKoo** [comment]
@ionutneagos 

> Can you please confirm if you are targeting correctly the .net version?

yes, I'm using .net 7

![image](https://user-images.githubusercontent.com/14313034/230527788-a27c2fac-6900-493b-a365-de45387a0932.png)



> A possible option could be a reference from another package which is targeting .net 6.

It's "Microsoft.EntityFrameworkCore" and "Microsoft.EntityFrameworkCore.SqlServer", they are targeting .net 6, and your package is using them, so could you please tell me how to fix the problem? to install the .net 6?
Thanks!

![image](https://user-images.githubusercontent.com/14313034/230530969-2eeb40de-e4db-4553-b762-bccf0e13f158.png)
![image](https://user-images.githubusercontent.com/14313034/230531014-b0b70f1d-b1ba-45f2-8edf-2ba96b58ba72.png)

**Comment by ionutneagos** [comment]
@OscarKoo - can you confirm if you have installed  Microsoft.EntityFrameworkCore 7.0.4 and Microsoft.EntityFrameworkCore.SqlServer on your project ( or infrastructure project) ?

**Comment by OscarKoo** [comment]
@ionutneagos 
1. follow your suggestions, I installed all these 3 three dependency packages (on the Program.cs project).

![image](https://user-images.githubusercontent.com/14313034/230612574-0ca7ce4a-5369-4b98-8416-c4f9b3ebdf2d.png)

2. I dropped the database, and let the application re-create it.
3. the first time, the program started successfully, and the index has been created.
4. I stopped and restarted the application, and then it failed, and got the exception again.

![image](https://user-images.githubusercontent.com/14313034/230613000-274ddf80-b2f7-449a-af8d-be76bd5b1f1f.png)
![image](https://user-images.githubusercontent.com/14313034/230613344-8ba377ae-2527-4b8f-91c3-f429f8ee3ef4.png)

What should I do then? I really like your package, it's great! hope you can solve the problem.

**Comment by ionutneagos** [comment]
Hi @OscarKoo, it's possible to share your repository with me? I'm not able to reproduce the issue. Maybe there are other properties and not the index is the issue...

**Comment by OscarKoo** [comment]
@ionutneagos 

> it's possible to share your repository with me?

sorry, it's not my personal repository, I cannot do that...

the issue only happens when I use "Include column", I can solve the problem by move the column from "Include column" to "Index column".
if you have no clue for now, I can get over it by moving the include column to index column. and thanks for your supporting these days.

**Comment by ionutneagos** [comment]
Thank you @OscarKoo for let me know about this. I will close for now and I will try to reproduce this issue based on your input.

**Comment by OscarKoo** [comment]
I knew how to solve the problem, which is drop the database! I think maybe you have taken the project structure or the namespace into the "snapshot", and if we changed the project structure or the namespace (even if we didn't change the table), the issue happens.
Could you please confirm the conclusion? it will be a disaster if we have to drop the production database after we changed the project structure ...

**Comment by ionutneagos** [comment]
hi @OscarKoo, 
just noticed your input. I will do a test based on your input

**Comment by OscarKoo** [comment]
`@OscarKoo - do you apply migration from assembly? Like builder.ApplyConfigurationsFromAssembly ?`

we have moved "EntityBase" and "EntityTypeConfigurationBase" these base classes to another place, which means all the Entites and EntityTypeConfigurations have to inherit them from another place.
we have moved "DbContext" to another place as well, which means we have to change "OnModelCreating" as well.

from:
`protected override void OnModelCreating(ModelBuilder modelBuilder)`
`{`
`    modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());`
`    base.OnModelCreating(modelBuilder);`
`}`

to: "ConfigAssembly" is a parameter that passed in, it address the correct assembly of EntityTypeConfigurations
`protected override void OnModelCreating(ModelBuilder modelBuilder)`
`{`
`    modelBuilder.ApplyConfigurationsFromAssembly(ConfigAssembly);`
`    base.OnModelCreating(modelBuilder);`
`}`

**Comment by OscarKoo** [comment]
@ionutneagos I have some new discoveries, I have tried to get snapshot information from table "__ContextSnapshot", and I found the root cause of the problem: the namespace does not exist anymore.
![image](https://github.com/ionutneagos/efcore-automaticmigrations/assets/14313034/a4a21991-7091-424d-8ae4-5924fb42d985)

so if you can provide a feature which is allow me to get the snapshot and replace the wrong namespace (before your code using it), and I believe it will solve the problem, thanks!
![image](https://github.com/ionutneagos/efcore-automaticmigrations/assets/14313034/6c3f89bb-a361-4fcb-b17e-06cdd0b80032)
