### ISSUE TITLE
The requested configuration is not stored in the read-optimized model, please use 'DbContext.GetService<IDesignTimeModel>().Model'.

### ISSUE THREAD

**Issue by OscarKoo** [ionutneagos/efcore-automaticmigrations#2]
@ionutneagos I found another issue, when I changed the column length (the column belongs to an index), and I got an Exception.

could you please help me on this? thanks!

![image](https://user-images.githubusercontent.com/14313034/232187342-cd36e747-5203-4a96-bc69-2835dae69720.png)

![image](https://user-images.githubusercontent.com/14313034/232187716-7e110ccf-eb0b-4a04-8b76-f0263f72b2e0.png)

**Comment by ionutneagos** [comment]
@OscarKoo , are you using vs 7.0.5?

**Comment by OscarKoo** [comment]
@ionutneagos I made a small project to reproduce the issue.
[CoreWebApi.zip](https://github.com/ionutneagos/efcore-automaticmigrations/files/11268908/CoreWebApi.zip)


1. you need to run the app first to create the database.
2. stop the app.
3. Change the length of column Area.Name;
4. run the app again.
5. you will see the error.

**Comment by OscarKoo** [comment]
@ionutneagos 
Have you got any clue to address the issue? I cannot get over it this time...

**Comment by MulticastingGit** [comment]
hi @OscarKoo  - sorry for this delay, I was caught with some stuff.... Published the fix in vs **7.0.5.1**
<PackageReference Include="EFCore.AutomaticMigrations" Version="7.0.5.1" />

**Comment by MulticastingGit** [comment]
@OscarKoo - Please confirm if is ok now. Thank you!

**Comment by ionutneagos** [comment]
hi @OscarKoo - sorry for this delay, I was caught with some stuff.... Published the fix in vs 7.0.5.1

<PackageReference Include="EFCore.AutomaticMigrations" Version="7.0.5.1" />

 Please confirm if is ok now. Thank you!

**Comment by OscarKoo** [comment]
awesome! it works! thank you @ionutneagos !!!

**Comment by ionutneagos** [comment]
@OscarKoo glad that works well now! I will close this issue
