### ISSUE TITLE
Conflicts with Z.EntityFramework.Plus.EFCore (7.21.0)

### ISSUE THREAD

**Issue by OscarKoo** [ionutneagos/efcore-automaticmigrations#3]
@ionutneagos 

I met another issue, this is a tough choice for me, hope you might have time to help me, thank you...

After I installed the package Z.EntityFramework.Plus.EFCore (7.21.0), I got the exception;
and If I remove Z.EntityFramework.Plus.EFCore, exception will disappear...
so I have to face the tough choice, only use EFCore.AutomaticMigrations, or only use Z.EntityFramework.Plus.EFCore...

![image](https://user-images.githubusercontent.com/14313034/235043015-91727fc1-e452-45d5-b817-b23b404b9cf5.png)

you can reproduce the issue with my last small repo, if you are interested on it

![image](https://user-images.githubusercontent.com/14313034/235044619-5de34587-cadd-4a94-8d8d-ca4d4d079902.png)

**Comment by ionutneagos** [comment]
@OscarKoo - I published the fix in 7.0.5.2 version. 

`<PackageReference Include="EFCore.AutomaticMigrations" Version="7.0.5.2" />`

Thank you for your involvement, you are helping me to make this package more robust!

**Comment by ionutneagos** [comment]
@OscarKoo , let me know please if this version works

**Comment by OscarKoo** [comment]
> let me know please if I can close this issue

@ionutneagos , your patch works! thank you!

I'm glad I could help, and I like your project very much!
