### ISSUE TITLE
Allow user to correct the snapshot before using it

### ISSUE THREAD

**Issue by OscarKoo** [ionutneagos/efcore-automaticmigrations#5]
if the user changed the namespace of "DbContext" or "Entities", it might cause the "Migrate" failed (https://github.com/ionutneagos/efcore-automaticmigrations/issues/1#issuecomment-1718707632), so it would be nice if there is an opportunity which is allow the user to modify the snapshot before using it

**Comment by ionutneagos** [comment]
@OscarKoo  - please take a look at vs 7.0.11. 

DbMigrationOptions expose a new property ( Dictionary) to allow update Update Snapshot.

**Comment by ionutneagos** [comment]
Released in 7.0.11
