### ISSUE TITLE
The name 'DeleteBehavior' does not exist in the current context.

### ISSUE THREAD

**Issue by webfletch** [ionutneagos/efcore-automaticmigrations#6]
Hi, I am trying to use your package after migrating from EF to EF Core as the Automatic Migrations in the old EF have always worked well for us.

I have added the following code which gets run manually in a method (we need to be able to basically press a button to run the migrations):

```
 MigrateDatabaseToLatestVersion.Execute(new OurDbContext(), new DbMigrationsOptions
 {
     AutomaticMigrationsEnabled = true,
     AutomaticMigrationDataLossAllowed = false
 });
```

The code above appeared to the run correctly the first time and created a table in the database called __ContextSnapshot (although it didn't make changes to the database tables I was expecting but that might be due to "AutomaticMigrationDataLossAllowed" being set to false), however, the next time that I tried to run the code again (without making any changes) I am getting the following error:

> _Compilation failed. Error: The name 'DeleteBehavior' does not exist in the current context;The type 'DeleteBehavior' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.EntityFrameworkCore.Abstractions, Version=7.0.15.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.;_

These are the dependencies I have installed and I have confirmed these are present in my "Bin" folder as well, especially the Microsoft.EntityFramework.Abstractions one (for some reason the "Microsoft.EntityFrameworkCore.Tools" doesn't get copied to the bin folder, not sure if that is an issue or not) :

    <PackageReference Include="EFCore.AutomaticMigrations" Version="6.0.10.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="7.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.15" />

**Comment by ionutneagos** [comment]
hi @webfletch ,

I noticed you are using EFC 7.0.15 and EFCore.AutomaticMigrations is vs 6.*. Can you please give a try with vs 7.*.*?

<PackageReference Include="EFCore.AutomaticMigrations" Version="7.0.11" />

Let me know please the result

**Comment by webfletch** [comment]
I am running .net 6 so cannot install version 7 as I believe that requires .net 7

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ionutneagos** [comment]
hi @webfletch , I was wondering if you managed to upgrade your solution to .NET 7 and if you still encounter the error.

**Comment by webfletch** [comment]
Hi @ionutneagos, no I am still working on migrating the system to .Net 6, I may look at moving to .Net 8 in the future once the upgrade is complete but for the time being I have removed this package and I am using manual migrations instead.
