### ISSUE TITLE
Need a minimal starter sample project 

### ISSUE THREAD

**Issue by aloksharma1** [ionutneagos/efcore-automaticmigrations#7]
Hello,
i found your lib through nuget, but i am not able to understand how it works. does it change table schema etc on runtime or do i need to generate migrations from ef commands? a minimal solution of how it works would be great.

thanks

**Comment by ionutneagos** [comment]
Hi @aloksharma1 ,

I have added a small sample project to the repository. The database changes are executed at runtime, so you don't have to generate manual migrations.

Please take a look at the sample project. Run the solution, update an existing entity, or add a new one, and then check the database. You should be able to see the updated tables. The approach is very similar to Entity Framework for .NET Framework.

https://github.com/ionutneagos/efcore-automaticmigrations?tab=readme-ov-file#sample-project 

Let me know your test result please.

**Comment by aloksharma1** [comment]
Thank you for the update.
